version: 2

jobs:
  "ar71xx-generic":
    working_directory: ~/code
    docker:
      - image: pexcn/docker-images:stretch-openwrt
    environment:
      OPENWRT_CONFIG_URL: https://raw.githubusercontent.com/openwrt-dev/configs/openwrt-18.06/ar71xx-generic
    steps:
      - checkout
      - run:
          name: Setup environment variables
          command: |
            echo 'export USE_CCACHE=1' >> $BASH_ENV
            echo 'export CCACHE_DIR="$HOME/code/ccache"' >> $BASH_ENV
      - restore_cache:
          key: openwrt-ar71xx-generic-20190619
      - run:
          name: Run build
          command: bash build.sh
      - save_cache:
          key: openwrt-ar71xx-generic-20190619
          paths:
            - openwrt-dl
            - ccache
      - store_artifacts:
          path: openwrt/bin
          destination: bin

  "ar71xx-tiny":
    working_directory: ~/code
    docker:
      - image: pexcn/docker-images:stretch-openwrt
    environment:
      OPENWRT_CONFIG_URL: https://raw.githubusercontent.com/openwrt-dev/configs/openwrt-18.06/ar71xx-tiny
    steps:
      - checkout
      - run:
          name: Setup environment variables
          command: |
            echo 'export USE_CCACHE=1' >> $BASH_ENV
            echo 'export CCACHE_DIR="$HOME/code/ccache"' >> $BASH_ENV
      - restore_cache:
          key: openwrt-ar71xx-tiny-20190619
      - run:
          name: Run build
          command: bash build.sh
      - save_cache:
          key: openwrt-ar71xx-tiny-20190619
          paths:
            - openwrt-dl
            - ccache
      - store_artifacts:
          path: openwrt/bin
          destination: bin

  "ramips-mt7620":
    working_directory: ~/code
    docker:
      - image: pexcn/docker-images:stretch-openwrt
    environment:
      OPENWRT_CONFIG_URL: https://raw.githubusercontent.com/openwrt-dev/configs/openwrt-18.06/ramips-mt7620
    steps:
      - checkout
      - run:
          name: Setup environment variables
          command: |
            echo 'export USE_CCACHE=1' >> $BASH_ENV
            echo 'export CCACHE_DIR="$HOME/code/ccache"' >> $BASH_ENV
      - restore_cache:
          key: openwrt-ramips-mt7620-20190619
      - run:
          name: Run build
          command: bash build.sh
      - save_cache:
          key: openwrt-ramips-mt7620-20190619
          paths:
            - openwrt-dl
            - ccache
      - store_artifacts:
          path: openwrt/bin
          destination: bin

  "x86-64":
    working_directory: ~/code
    docker:
      - image: pexcn/docker-images:stretch-openwrt
    environment:
      OPENWRT_CONFIG_URL: https://raw.githubusercontent.com/openwrt-dev/configs/openwrt-18.06/x86-64
    steps:
      - checkout
      - run:
          name: Setup environment variables
          command: |
            echo 'export USE_CCACHE=1' >> $BASH_ENV
            echo 'export CCACHE_DIR="$HOME/code/ccache"' >> $BASH_ENV
      - restore_cache:
          key: openwrt-x86-64-20190619
      - run:
          name: Run build
          command: bash build.sh
      - save_cache:
          key: openwrt-x86-64-20190619
          paths:
            - openwrt-dl
            - ccache
      - store_artifacts:
          path: openwrt/bin
          destination: bin

workflows:
  version: 2
  build:
    jobs:
      - "ar71xx-generic"
      - "ar71xx-tiny"
      - "ramips-mt7620"
      - "x86-64"
