version: 2

jobs:
  "ar71xx-generic":
    working_directory: ~/ci
    docker:
      - image: pexcn/docker-images:stretch-openwrt
    environment:
      OPENWRT_CONFIG_URL: https://raw.githubusercontent.com/openwrt-dev/configs/openwrt-18.06/ar71xx-generic
      OPENWRT_BRANCH: openwrt-18.06
    steps:
      - checkout
      - run:
          name: Run build
          command: bash build.sh
      - run:
          name: Deploy
          command: bash deploy.sh
      - store_artifacts:
          path: openwrt/bin
          destination: bin

  "ar71xx-tiny":
    working_directory: ~/ci
    docker:
      - image: pexcn/docker-images:stretch-openwrt
    environment:
      OPENWRT_CONFIG_URL: https://raw.githubusercontent.com/openwrt-dev/configs/openwrt-18.06/ar71xx-tiny
      OPENWRT_BRANCH: openwrt-18.06
    steps:
      - checkout
      - run:
          name: Run build
          command: bash build.sh
      - run:
          name: Deploy
          command: bash deploy.sh
      - store_artifacts:
          path: openwrt/bin
          destination: bin

  "ramips-mt7620":
    working_directory: ~/ci
    docker:
      - image: pexcn/docker-images:stretch-openwrt
    environment:
      OPENWRT_CONFIG_URL: https://raw.githubusercontent.com/openwrt-dev/configs/openwrt-18.06/ramips-mt7620
      OPENWRT_BRANCH: openwrt-18.06
    steps:
      - checkout
      - run:
          name: Run build
          command: bash build.sh
      - run:
          name: Deploy
          command: bash deploy.sh
      - store_artifacts:
          path: openwrt/bin
          destination: bin

  "x86-64":
    working_directory: ~/ci
    docker:
      - image: pexcn/docker-images:stretch-openwrt
    environment:
      OPENWRT_CONFIG_URL: https://raw.githubusercontent.com/openwrt-dev/configs/openwrt-18.06/x86-64
      OPENWRT_BRANCH: openwrt-18.06
    steps:
      - checkout
      - run:
          name: Run build
          command: bash build.sh
      - run:
          name: Deploy
          command: bash deploy.sh
      - store_artifacts:
          path: openwrt/bin
          destination: bin

workflows:
  version: 2
  build:
    jobs:
      - "ar71xx-generic"
      - "ar71xx-tiny"
      - "ramips-mt7620"
      - "x86-64"
