name: Build

on:
  push:
  workflow_dispatch:
    inputs:
      upload_release:
        description: 'Whether to upload binaries to releases'
        required: true
        default: '0'

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: pexcn/docker-images:buster-openwrt
      volumes:
        - /usr/local:/usr/local
        - /usr/lib/google-cloud-sdk:/usr/lib/google-cloud-sdk
        - /usr/share/dotnet:/usr/share/dotnet
        - /usr/share/swift:/usr/share/swift
        - /opt/az:/opt/az
        - /opt/google:/opt/google
        - /opt/microsoft:/opt/microsoft
        - /opt/pipx:/opt/pipx
        - /opt/hostedtoolcache:/opt/hostedtoolcache
    env:
      TZ: Asia/Taipei
      BUILD_REPO: https://github.com/openwrt-dev/openwrt.git
      BUILD_PROFILE: ${{ matrix.PROFILE }}
    strategy:
      fail-fast: false
      matrix:
        PROFILE:
          - ath79-generic
          - ath79-tiny
          - ramips-mt7620
          - x86-64

    steps:
      - name: Maximize disk space
        uses: pexcn/maximize-disk-space@v1
        with:
          use-system-docker: false

      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Make build cache
        uses: actions/cache@v3
        with:
          path: /builder/.ccache
          key: ${{ runner.os }}-${{ github.ref_name }}-${{ env.BUILD_PROFILE }}-${{ github.sha }}
          restore-keys: ${{ runner.os }}-${{ github.ref_name }}-${{ env.BUILD_PROFILE }}-

      - name: Build firmware
        run: ./build.sh

      - name: Upload to Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.BUILD_PROFILE }}
          path: openwrt/bin

      - name: Upload to Releases
        if: (github.event_name == 'push' && startsWith(github.event.head_commit.message, '[release] ')) || (github.event.inputs.upload_release == 1)
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: ${{ env.BUILD_PROFILE }}.tar.gz
