name: Build

on:
  push:
  workflow_dispatch:
    inputs:
      verbose_log:
        description: 'Whether to enable verbose build log'
        required: true
        default: '0'

env:
  TZ: Asia/Taipei

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: pexcn/docker-images:buster-openwrt
      #options: --user builder
    env:
      CONFIG_URL: https://raw.githubusercontent.com/openwrt-dev/configs/openwrt-19.07/${{ matrix.ARCH }}
      VERBOSE_LOG: ${{ github.event.inputs.verbose_log }}
    strategy:
      fail-fast: false
      matrix:
        ARCH:
          - ath79-generic
          - ath79-tiny
          - ramips-mt7620
          - x86-64
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run build
        run: ./build.sh $VERBOSE_LOG
      - name: Upload to Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.ARCH }}
          path: openwrt/bin
